#!/bin/bash

tmp=$(mktemp)
function finish { rm -rf $tmp; }
trap finish EXIT
curl -s -L -o $tmp https://raw.githubusercontent.com/aporeto-se/aporeto-installer/master/src/aporeto_real_install
chmod +x $tmp
$tmp $@
