#!/bin/bash
# This script is written to be stable over long periods of time. It does this by downloading and executing the
# real script at each execution. You can include this script in a golden image.

cd $(dirname $0)
curl -s -L -o install_all https://raw.githubusercontent.com/aporeto-se/aporeto-installer/master/src/install_all
chmod +x install_all
./install_all $@
