#!/bin/bash
# This script is written to be stable over long periods of time. It does this by downloading and executing the
# real script at each execution. You can include this script in a golden image.

tmp=$(mktemp)
function finish { rm -rf $tmp; }
trap finish EXIT
curl -s -L -o install_enforcerd https://raw.githubusercontent.com/aporeto-se/aporeto-installer/master/src/libinstall
chmod +x $tmp
$tmp $@
