#!/bin/bash

curl -s -L -o install_enforcerd https://raw.githubusercontent.com/aporeto-se/aporeto-installer/master/src/install_enforcerd
curl -s -L -o install_tools https://raw.githubusercontent.com/aporeto-se/aporeto-installer/master/src/install_tools
chmod +x install_enforcerd
chmod +x install_tools

./install_enforcerd $@
./install_tools $@
